### PR TITLE
BUG/TST: Handle invlaid coeffs in waverecn

### PR DESCRIPTION
**Pull request by kwohlfahrt**
Correctly handle missing coefficients in waverecn, as they are treated in idwtn.

### CODE REVIEW

**Comment by kwohlfahrt** [comment]
Don't merge, this is hugely wrong. It discards empty levels.

**Comment by kwohlfahrt** [comment]
OK, better now.

**Comment by grlee77** [comment]
thanks Kai.  I am on vacation until the 14th, so it will be a while untile
I take a closer look

**Comment by grlee77** [comment]
@kwohlfahrt
This looks good to me.  Two questions:
1. Is there a use case where one would provide empty levels?
2. Do you think we should raise a warning if the detail coefficient dictionary has extra keys that would be discarded by `_fix_coeffs`?

**Comment by kwohlfahrt** [comment]
1. No idea to be honest, not for my use. But if we allow keys to be missing, then it should do the right thing when all keys are missing.
2. I think so. Checking at the beginning what `ndim` is and raising an exception if they differ is probably also a good idea. Currently it just uses the longest valid one, which might silently eat some errors.

**Comment by grlee77** [comment]
@kwohlfahrt 
I am merging this PR as is.  I will look into adding a warning if any coefficients in the detail coefficient dictionary have an invalid key or are None and an exception if any of the coefficient arrays have the wrong number of dimensions.

**Comment by grlee77** [comment]
https://www.python.org/dev/peps/pep-0420/

**Pull request merged**
